<?= "<?xml version=\"1.0\" ?>\n"; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<? foreach ($this->getLinkTags() as $link): ?>
		<link <?= $link; ?> />
		<? endforeach; ?>

		<? foreach ($this->getScriptTags() as $script): ?>
		<script <?= $script; ?>></script>
		<? endforeach; ?>

		<title>
			<?= $this->getProject(); ?> ::
			<?= $this->getTitle(); ?>
		</title>
	</head>

	<body>
