<?php echo $this->partial('components/_topMenu.phtml'); ?>

<h1>Projects</h1>

<h2>Websites</h2>
<ul>
	<li><h3><a href="http://www.aospace.com">Aospace</a></h3>
		This site has gone through many versions, and in each I learn a little more.
		In its current form, it's an open source project with each page conforming to
		valid XHTML 1.0 Strict standards built using Zend Framework 1.9. The main
		purpose of this project is to be a personal website.</li>

	<li><h3><a href="http://scenicroute.aospace.com">Scenicroute</a></h3>
		Created for a good friend, this page was built under a custom made framework
		and designed to be a minimalistic personal website that can can also be used
		to blog with.</li>

	<li><h3><a href="http://taleschannel.org">Taleschannel</a></h3>
		Originally suppose to be a mini CMS, the project never really took flight due to
		logistics. Code was written but never published. As it currently stands,
		the domain is used to host random files by its administrator.</li>

	<li><h3><a href="http://aozaki.com/western/mis314">Symons Books</a></h3>
		Class assignment built on a custom framework work. We were given half a month
		to plan and a month to write it. I did the whole thing (with no initial planning)
		in roughly 24 hours.</li>

	<li><h3>ResTek Applications</h3>
		Most ResTek applications that I maintained and/or created were internal.
		Examples include a custom ticket tracking system, basic inventory tracking
		system (for the resident halls), resident bandwidth statistics, and helping
		to create one of Western Washington University's first bilingual web applications.</li>
</ul>

<h2>Code</h2>
<ul>
	<li><h3><a href="/projects/download/code/db">Database Connections</a></h3>
		Making a site in PHP and need to query a MySQL server? Use this to simplify
		the process and avoid SQL injections at the same time</li>
</ul>
