<div id="navbar-top">
	<ul>
		<li><a href="<?= $this->url(array('action'=>'index')); ?>">home</a></li>
		<li><a href="<?= $this->url(array('action'=>'about')); ?>">about me</a></li>
		<li><a href="<?= $this->url(array('action'=>'code')); ?>">code share</a></li>
		<li><a href="<?= $this->url(array('action'=>'site_status')); ?>">site status</a></li>
		<li><a href="http://aozaki.com">development</a></li>
		<li><a href="<?= $this->url(array('action'=>'contact')); ?>">contact</a></li>
	</ul>
</div>
