<? $this->header->setTitle("Code Share")
                ->addLinkTag("rel='stylesheet' type='text/css' href='/views/css/code.css'")
                ->addLinkTag("rel='stylesheet' type='text/css' href='http://library.aospace.com/css/jquery-ui.css' rel='stylesheet' ")
                ->addScriptTag("src='/views/js/code.js' type='text/javascript'")
?>

<h1>Code Share</h1>
<?= $this->partial('index/_top-navbar.phtml'); ?>

<div class="content-box">
	Here is a personal collection of code that I have found incredibly useful at one point or another.
	I strongly believe in open source and as such, I feel a need to share some of the code
	that I have written. All code here is released under the 
	<a href="http://www.opensource.org/licenses/mit-license.php">MIT License</a>.
	If you have any questions about my code or would like to suggest an improvement, please let me know.
</div>

<div class="content-box">
	<h2>Self Created</h2>

	<div class="code-item">
		<h3>PHP: Autoloader</h3>
		<ul>
			<li><a href="/views/scripts/index/code/autoloader/description.htm">Description</a></li>
			<li><a href="/views/scripts/index/code/autoloader/example.htm">Example</a></li>
		</ul>
	</div>

	<div class="code-item">
		<h3>PHP: Backtrace</h3>
		<ul>
			<li><a href="/views/scripts/index/code/backtrace/description.htm">Description</a></li>
			<li><a href="/views/scripts/index/code/backtrace/example.htm">Example</a></li>
		</ul>
	</div>

	<div class="code-item">
		<h3>PHP: Database</h3>
		<ul>
			<li><a href="/views/scripts/index/code/database/description.htm">Description</a></li>
			<li><a href="/views/scripts/index/code/database/example.htm">Example</a></li>
		</ul>
	</div>

	<div class="code-item">
		<h3>PHP: Header</h3>
		<ul>
			<li><a href="/views/scripts/index/code/header/description.htm">Description</a></li>
			<li><a href="/views/scripts/index/code/header/example.htm">Example</a></li>
		</ul>
	</div>
</div>
