<? $this->header->setTitle("Contact"); ?>

<div class="left">
	<h1>Contact</h1>
	<div class="left-content">
		<p>
			Thank you for taking the time to comment or ask questions.
			If you experience any difficulties using this form, feel
			free to email me directly at symons(at) aospace (dot) com
		</p>

		<? if ($_SESSION['error']) {
			$error = new Library_Errorbox;
			$error->setMessage($_SESSION['error'])
			      ->render();
			unset($_SESSION['error']);
			}
		?>
		<? if ($_SESSION['success']) {
			$error = new Library_Successbox;
			$error->setMessage($_SESSION['success'])
			      ->render();
			unset($_SESSION['success']);
			}
		?>
		<form method="post" action="/index/contact">
			<p>
				<label for="name">Your Name</label><br/>
				<input type="text" id="name" name="name" />
			</p>
			<p>
				<label for="email">Your Email</label><br/>
				<input type="text" id="email" name="email" />
			</p>
			<p>
				Comments:<br/>
				<textarea name="comments" rows="" cols=""></textarea>
			</p>
			<p>
				<input type="hidden" name="action" value="contact" />
				<input type="submit" value="Submit &gt;&gt;" />
			</p>
		</form>
	</div>

	<div class="container center">
		<?= $this->partial('index/_bottom-navbar.phtml'); ?>
	</div>
</div>

<div class="right">
	<div class="photo-frame">
		<img src="/images/sideimages/deer.jpg" alt="Deer" />
	</div>

	<div class="quote">
		"Not everything that counts can be counted, and not
		everything that can be counted counts."
	</div>

	<div class="center">
		<?= $this->partial('index/_buttons.phtml'); ?>
	</div>
</div>
