<?php if ($this->photos === false) : ?>
	Error retrieving photos
<?php else : ?>
	<?php foreach ($this->photos as $key => $photo): ?>
		<?php if ($key == 4) : ?><br /><?php endif ?>
		<a href="http://www.flickr.com/photos/<?php echo $photo->ownername; ?>/<?php echo $photo->id; ?>/">
			<img class="flickrImage" src="<?php echo $photo->Square->uri; ?>" alt="flickr photo" />
		</a>
	<?php endforeach ?>
<?php endif ?>
