<div class="sideimage">
	<img src="/images/sideimage-road.jpg" alt="sideimage" />
	<ul class="menu">
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'about')); ?>">about</a></li>
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'code')); ?>">code</a></li>
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'resume')); ?>">resume</a></li>
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'contact')); ?>">contact</a></li>
	</ul>
</div>

<img id="top-right" src="/images/tmp.jpg" />

<h1>Welcome to Aospace!</h1>
<p class="bold">
	Aospace is a personal website created to express my interest in web design
	&amp; web programming.
</p>
<p>
	This site goes through many redesigns as my programming ability develops.
	At the very least, I hope this site will give insperation to what can be done when
	you put your mind to something.
</p>

<a href="<?php echo $this->url(array('controller' => 'about')); ?>">read more...</a>

<div class="hr">&nbsp;</div>

<div id="updates" class="right hr-left">
	<?php if ($this->tweets === false) : ?>
		Error retrieving tweets
	<?php else : ?>
		<ul>
			<?php foreach($this->tweets->status as $tweet) : ?>
			<li>
				<?php echo $tweet->text; ?><br />
				<?php echo $this->tweet->created_at; ?>
			</li>
			<?php endforeach ?>
		</ul>
	<?php endif ?>
	<a href="http://www.twitter.com/aospace">see more...</a>
</div>

<?php if ($this->photos === false) : ?>
	Error retrieving photos
<?php else : ?>
	<?php foreach ($this->photos as $key => $photo): ?>
		<?php if ($key == 4) : ?><br /><?php endif ?>
		<a href="http://www.flickr.com/photos/<?php echo $photo->ownername; ?>/<?php echo $photo->id; ?>/">
			<img class="flickrImage" src="<?php echo $photo->Square->uri; ?>" alt="flickr photo" />
		</a>
	<?php endforeach ?>
<?php endif ?>
<br />
<a href="http://www.flickr.com/photos/<?php echo $photo->ownername; ?>">see more...</a>
