<div class="sideimage">
	<img src="/images/sideimage-road.jpg" alt="sideimage" />
	<ul class="menu">
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'about')); ?>">about</a></li>
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'projects')); ?>">projects</a></li>
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'resume')); ?>">resume</a></li>
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'contact')); ?>">contact</a></li>
	</ul>
</div>

<img id="top-right" src="/images/indexTopRight.jpg" />

<h1>Welcome to Aospace!</h1>
<p class="bold">
	Aospace is a personal website created to express my interest in web design
	&amp; web programming.
</p>
<p>
	This site goes through many redesigns as my programming ability develops.
	At the very least, I hope this site will give insperation to what can be done when
	you put your mind to something.
</p>

<a href="<?php echo $this->url(array('controller' => 'about')); ?>">read more...</a>

<div class="hr">&nbsp;</div>

<div id="updates" class="right hr-left">
	<?php if ($this->tweets->error) : ?>
		<div>Error retrieving tweets</div>
	<?php else : ?>
		<ul>
			<?php foreach($this->tweets->status as $tweet) : ?>
			<li>
				<?php echo $tweet->text; ?><br />
				<?php echo $this->tweet->created_at; ?>
			</li>
			<?php endforeach ?>
		</ul>
	<?php endif ?>
	<a href="http://www.twitter.com/aospace">see more...</a>
</div>


<div id="flickrPhotos"><img src="/images/ajaxLoadingBar.gif" alt="loading" /></div>
<a href="http://www.flickr.com/photos/<?php echo $photo->ownername; ?>">see more...</a>
