<div class="center">
	<a href="http://www.php.net">
		<img src="/images/buttons/php.png" alt="php" /></a>
	<a href="http://validator.w3.org/check?uri=referer">
		<img src="/images/buttons/w3c-html401.gif" alt="w3c-html" /></a>
	<a href="http://jigsaw.w3.org/css-validator/check/referer">
		<img src="/images/buttons/w3c-css.jpg" alt="w3c-css" /></a>
	<a href="http://www.opera.com/">
		<img src="/images/buttons/opera.png" alt="opera" /></a>
	<a href="http://www.mozilla.com/">
		<img src="/images/buttons/firefox.gif" alt="firefox" /></a>
</div>

