<?php echo $this->partial('components/_topMenu.phtml'); ?>

<img class="right" src="/images/profile.png" alt="profile image" />
<h1>About me...</h1>

<h2>Web</h2>
In short, I'm a web nut. I created my first web page with I was 10 years old and have been addicted ever since.
I am very proud to say most all my knowledge of web programming &amp; design has been without formal training.

<h2>Language</h2> While I was in high school I was introduced to Japanese popular music by a good friend. I thought the language
sounded pretty so, not knowing a lick of Japanese, I started to research the language. In the end, I found learning a
language because of the way it sounds is a self-defeating goal. I must say though, Japanese has introduced me to more
opportunities than I could have ever first imagined. I've had the chance to help teach English in the classroom,
allowed to study abroad, helped make one of the first bilingual web applications for Western Washington University, but
most importantly, Japanese has allowed me to interact with some of the most interesting people I've meet. I don't dare
claim to be fluent in the language but it does play a large part in my daily life.

<h2>Beliefs</h2>
Most people wish to tell others what they believe in but rarely wish to hear the opposite. If you are reading this
section I assume you are of the minority. I was raised Christian but when I finally started to think for myself, I
quickly dropped the belief. Don't get me wrong, there are a lot of good values in Christianity but there are too many
smaller things that don't seem to make sense. One of those things is the clear distinction between right and
wrong. I choose not to believe in right or wrong. Instead, I like to think there are only different paths leading to
different futures and each person can choose which path they wish to take.
