<div class="top-menu">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => 'index')); ?>">home</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'about')); ?>">about</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'code')); ?>">code</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'resume')); ?>">resume</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'contact')); ?>">contact</a></li>
	</ul>
</div>
