<?php echo $this->partial('components/_topMenu.phtml'); ?>

<h1>David Symons</h1>

<fieldset class="right">
	<legend>Contact</legend>
	<ul>
		<li><a href="http://www.linkedin.com/in/davidvsymons">Linkedin</a></li>
		<li><a class="plain" href="<?php echo $this->url(array('controller' => 'contact')); ?>">Email</a></li>
	</ul>
	** Phone number and mailing address available upon request to those seeking work related communications.
</fieldset>

<h2>Education</h2>
<ul>
	<li><h3>Bachelors of Science in Computer Science</h3>
		<a href="http://www.wwu.edu">Western Washington University</a>, March 2009</li>
	<li><h3>Associates in Arts &amp; Sciences</h3>
		<a href="http://bellevuecollege.edu">Bellevue Community College</a>, April 2006</li>
	<li><h3>Intensive Japanese Study</h3>
		<a href="http://www.kcpinternational.com">KCP International Language Institute</a>, Tokyo, Japan, 2006</li>
</ul>

<hr />

<h2>Knowledge</h2>
<ul class='left clear-right'>
	<li>PHP / Python</li>
	<li>C / C++ / C# / JAVA</li>
	<li>Javascript</li>
</ul><ul class='left'>
	<li>MySQL</li>
	<li>DHCP / DNS / TCP/IP</li>
	<li>Linux / Windows</li>
</ul><ul class='left'>
	<li>CVS / SVN / GIT</li>
	<li>VIM</li>
	<li>Conversational Japanese</li>
</ul>

<hr />

<h2>Work Experience</h2>
<ul id="experience">
	<li><strong>Software Developer</strong>
		<a href="http://pspinc.com">Pacific Software Publishing, Inc.</a> 2009 - Present
		<ul class="bullets">
			<li>Use PHP, MySQL, &amp; Apache to build, maintain, and modify applications as needed</li>
			<li>Communicated with staff to ensure software was built to specification</li>
		</ul></li>
	<li><strong>Web Application Developer</strong>
		<a href="http://restek.wwu.edu">Residential Technology Service</a> 2007 – 2009
		<ul class="bullets">
			<li>Use PHP, Python, and MySQL to develop, modify, and maintain new and existing web based projects</li>
			<li>Administered the 5000+ node residential network for Western Washington University</li>
			<li>Interfaced with staff members to test and refine both new and existing scripts and projects</li>
		</ul></li>
	<li><strong>Teaching Assistant</strong>
		<a href="http://www.cs.wwu.edu/">Western Washington University Computer Science Dept</a> 2007
		<ul class="bullets">
			<li>Explained and answered questions pertaining to basic website development</li>
			<li>Graded student assignments</li>
			<li>Led student labs and assisted with assignments</li>
		</ul></li>
	<li><strong>Shift Manager</strong>
		<a href="http://www.jackinthebox.com/">Jack In The Box Inc.</a>  2001 – 2006
		<ul class="bullets">
			<li>Handled financial transactions and opening/closing day paperwork</li>
			<li>Ensured all state and company regulations were being followed</li>
			<li>Trained employees in day to day operations</li>
		</ul></li>
</ul>

<hr />

<h2>Extra Curricular Activities</h2>
<ul>
	<li><strong>Japanese Conversation Club</strong> 2008-2009</li>
	<li><strong>Asia University America Program Campus Friend Volunteer</strong> 2008-2009</li>
	<li><strong>Classroom Volunteer for Asia University America Program</strong> 2007-2009</li>
</ul>
