<div id="noIE" class="notice">
	<img src="/images/ie6nomore-cornerx.jpg" alt="Close this notice" class="cornerx"/>
	<img src="/images/ie6nomore-warning.jpg" alt="IE6 no more warning" class="left"/>
	<div class="content">
		<h3> You are using an outdated browser</h3>
		For a better experience using this site, please upgrade<br />
		to a modern web browser
	</div>
	<a href="http://www.mozilla.com/en-US/">
		<img src="/images/ie6nomore-firefox.jpg" alt="Get Firefox 3.5" class="left" /></a>
	<a href="http://www.apple.com/safari/">
		<img src="/images/ie6nomore-safari.jpg" alt="Get Safari 4" class="left" /></a>
	<a href="http://www.google.com/chrome">
		<img src="/images/ie6nomore-chrome.jpg" alt="Get Google Chrome" class="left" /></a>
	<a href="http://www.opera.com/">
		<img src="/images/ie6nomore-opera.jpg" alt="Get Opera 10" class="left" /></a>
</div>
