<?= "<?xml version=\"1.0\" ?>\n"; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php foreach ($this->header->getLinkTags() as $link): ?>
		<link <?php echo $link; ?> />
		<?php endforeach; ?>

		<?php foreach ($this->header->getScriptTags() as $script): ?>
		<script <?php echo $script; ?>></script>
		<?php endforeach; ?>

		<title>
			Symons ::
			<?php echo $this->header->getProject(); ?> ::
			<?php echo  $this->header->getTitle(); ?>
		</title>
	</head>

	<body>
		<!-- [if IE]>
		<?php echo $this->partial('_noIE.phtml'); ?>
		<![endif]-->

		<!-- No script -->
		<?php echo $this->partial('_noScript.phtml'); ?>

		<div id="content">
			<?php echo $this->layout()->content ?>
		</div>

		<div id="footer">
			<strong>Note:</strong> All content has been created by<br/>
			David Symons however none of it is<br/>
			copyrighted. Please be kind and<br/>
			don't steal my work. Thanks.
		</div>
	</body>
</html>
